# Generated by Django 4.0.6 on 2023-06-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_booking'),
        ('room', '0002_guest_alter_booking_guest_alter_refund_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.guest'),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
