# Generated by Django 4.0.6 on 2023-05-26 00:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=9998887771, max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
